### ISSUE TITLE
🐞 python: `Service.start()` and `Service.stop()` now throw an exception

### ISSUE THREAD

**Issue by logan-hcg** [dagger/dagger#10447]
### What is the issue?

When manually starting and stopping services, for example like https://docs.dagger.io/api/services/#start-and-stop-services, the code will fail with an error:

```
AttributeError: type object 'Client' has no attribute 'from_context'. Did you mean: 'from_connection'?
```

This appears to be because `Service.start()` and `Service.stop()` are still using `Client.from_context()`, which has been removed:

https://github.com/dagger/dagger/blob/v0.18.8/sdk/python/src/dagger/client/gen.py#L9156-L9195

Other functions, like `Service.ports()` previously also used `Client.from_context()`, but no longer:

* v0.16.3: https://github.com/dagger/dagger/blob/v0.16.3/sdk/python/src/dagger/client/gen.py#L7742-L7761
* v0.18.8: https://github.com/dagger/dagger/blob/v0.18.8/sdk/python/src/dagger/client/gen.py#L9150-L9154

### Dagger version

0.18.8

### Steps to reproduce

Run this repro code:

```python
import asyncio
import sys

import dagger


async def main():
    async with dagger.Connection(dagger.Config(log_output=sys.stderr)) as client:
        redis_srv = (
            client
            .container()
            .from_("redis")
            .with_exposed_port(6379)
            .as_service()
        )

        await redis_srv.start()


asyncio.run(main())
```

This _does_ work with `dagger-io==0.16.3`

**Comment by helderco** [comment]
OMG, how did I miss this? 😱

Thanks for reporting @logan-hcg, I'll fix it right away. 🙏
