### ISSUE TITLE
🐞 rust dagger_sdk newest *patch* release contains breaking changes.

### ISSUE THREAD

**Issue by vivax3794** [dagger/dagger#11025]
### What is the issue?

Version `0.18.17` introduced the `NoGitAutoIgnore` argument, which is even highlighted in the releases as a breaking feature. Which with the rust sdk specifically means code no longer compiles without changes, which is not a good thing considering unless locked to a specific version cargo will happily update to newer patch versions. 

Honestly I get that the change isnt too breaking for most of the sdks, due to optional arguments etc, but for rust which doesnt have that, adding a new struct field is a breaking change unless the struct is marked as `#[non_exhaustive]` (which is specifically for "additions to this struct arent semver breaking", which will prevent users from creating the struct without using `..default()` etc).

And I dont mean breaking as in changes behavior, but breaking as in wont compile anymore. 

### Dagger version

0.18.17

### Steps to reproduce

Have code using `HostDirectoryOpts` that compiles on `0.18.16` and try compiling with `0.18.17`

### Log output

error[E0063]: missing field `no_git_auto_ignore` in initializer of `HostDirectoryOpts<'_>`
  --> dagger_pipeline/src/main.rs:72:17
   |
72 |                 HostDirectoryOpts {
   |                 ^^^^^^^^^^^^^^^^^ missing `no_git_auto_ignore`

error[E0063]: missing field `no_git_auto_ignore` in initializer of `HostDirectoryOpts<'_>`
   --> dagger_pipeline/src/main.rs:152:21
    |
152 |                     dagger_sdk::HostDirectoryOpts {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `no_git_auto_ignore`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `dagger_pipeline` (bin "dagger_pipeline") due to 2 previous errors
