### ISSUE TITLE
Generated Go API clients are not usable as generated

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#13805]
## Context

`dagger api client` generates a typed Go client for a module. First real use: `dagger/dagger`'s own Go e2e harness, with clients for `toolchains/engine-dev` and `toolchains/cli-dev`.

The shape we are converging on is **one package = one generated client = one module**:

```go
import (
	"myproject/internal/dagger/engine-dev"
	"myproject/internal/dagger/cli-dev"
)

dag, err := dagger.Connect(ctx)
defer dag.Close()

engine := enginedev.New(dag)
cli := clidev.New(dag)
```

The import block is the list of modules a program uses. A generated client is a typed view over a `*dagger.Client` the caller owns: it binds one module, does not connect, and has no lifecycle.

This is also where in-module codegen should end up, so that calling a module is the same whether you are inside a module or not.

## Problem

A generated client does not compile as generated, and the generated code assumes it is the only client in the program.

**Assumes it is alone**

| | |
| --- | --- |
| dagger/go-sdk#17 | every client is `package dagger`, so two collide |
| dagger/go-sdk#18 | every client redeclares core, so `clidev.File` ≠ `enginedev.File` |
| dagger/go-sdk#19 | every client opens its own session, so objects cannot cross |

These are not polish. One package per module guarantees several packages, and several packages only work if all three are fixed.

**Go module is unfinished**

| | |
| --- | --- |
| dagger/go-sdk#21 | does not compile until you edit the parent `go.mod` by hand |
| dagger/go-sdk#22 | module is named `engine-dev`, which is not a path, and defeats `internal/` |
| dagger/go-sdk#20 | cannot build on its own: no `go.sum`, no replace for a local SDK |

## Solution

Per issue. #21 first: until it is fixed a generated client does not compile at all, and the normal Go recovery for an unresolved import cannot fix it.

#22 before #21, so the require and replace #21 writes use the final module name rather than one #22 then invalidates.

### What we are not doing

**One `dag` object with every module mounted on it**, the way in-module codegen works today. It hides which modules a file actually uses, and reads as a service locator rather than Go. One package per module keeps the import block honest.

**A default global client**, so callers need not thread `dag`. `dagger.io/dagger/dag` already holds one, but it hardcodes its connection options and exports no accessor. Keeping explicit as the only path keeps the load-bearing surface small; a default can be added later without changing anything generated.
