### ISSUE TITLE
🐞 Failed to access module when transferring secret

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#10776]
### What is the issue?

Originally reported by @skycaptain in https://discord.com/channels/707636530424053791/1396132812377296936/1396164598670819398.

### Dagger version

v0.18.13 

### Steps to reproduce

See the repro: https://github.com/skycaptain/dagger-issue-passing-secrets

In v0.18.12:

```
$ dagger -m ./module-b call job --netrc-file 'file:dagger.json' run
▶ connect 1.5s
▶ load module: ./module-b 19.5s
● parsing command line arguments 0.0s

● moduleB: ModuleB! 0.7s
● .job(
  ┆ netrcFile: secret(uri: "file://dagger.json"): Secret!
  ): ModuleBJob! 0.7s
▶ .run: Void 3.6s
```

While in v0.18.14:

```
$ dagger -m ./module-b call job --netrc-file 'file:dagger.json' run
▶ connect 0.2s
▶ load module: ./module-b 5.1s
● parsing command line arguments 0.0s

● moduleB: ModuleB! 0.7s
✘ .job(
  ┆ netrcFile: secret(uri: "file://dagger.json"): Secret!
  ): ModuleBJob! 0.7s ERROR
! failed to create secret transfer post call: failed to load secret instances: load moduleB.job(netrcFile: {secret(uri: "file://dagger.json"): Secret!}).builder.netrcFile: Secret: load: load base: load base: load base: Call: Query has no such
  field: "moduleB"
[run] ERROR task failed
```

**Comment by jedevc** [comment]
Bisected to #10620 - cc @sipsma.

**Comment by GeoffBarrett** [comment]
I am still seeing this error in `0.18.14` where I am providing the module an optional secret.

```
ailed to create secret transfer post call: failed to load secret instances: load daggerCommon(paramFile: {host.directory(path: "/path", include: ["files.json"], noCache: false).file(path: "file.json"): File!}, gfToken: {secret(uri: "env://ENV_VAR"): Secret!}, source: {host.directory(path: "/path"): Directory!}, isPrimaryRunner: true, dockerUsername: {secret(uri: "env://ANOTHER_ENV_VAR"): Secret!}, dockerPassword: {secret(uri: "env://ENV_VAR_AGAIN"): Secret!}).dockerUsername: Secret: load: load base: Call: Query has no such field: "daggerCommon"
```

`daggerCommon` is the name of the entrypoint module in this case and I am using Python.

Is there a recommended way of dealing with optional secrets for the time being?

**Comment by skycaptain** [comment]
> Is there a recommended way of dealing with optional secrets for the time being?

According to Discord discussions, v0.18.15 is expected to be released soon, though no specific dates have been committed to. Depending on the project's requirements, I either downgraded to v0.18.12 or upgraded to HEAD for the time being.
